services:

  # mariadb container ------------------------------------------------------------

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb/
    volumes:
      - database:/var/lib/mysql/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env

  # wordpress container ------------------------------------------------------------

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb

  # nginx container ------------------------------------------------------------

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx/
      args:
        CERT_FOLDER: ${CERT_FOLDER}
        CERTIFICATE: ${CERTIFICATE}
        KEY: ${KEY}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        COMMON_NAME: ${COMMON_NAME}
    ports:
      - '443:443'
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress

# volumes --------------------------------------------------------------------

volumes:

  # database
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/database

  # wordpress files
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress_files

# networks --------------------------------------------------------------------

networks:
  all:
    driver: bridge